# Metadata about this component, to be used in the CMS
spec:
  structures:
    - nav_blocks
  label: Nav Item
  description: A single navigation item that can link to a page or contain sub-navigation.
  icon: link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  href: ""
  label: ""
  defaultOpen: false
  navBlocks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  href: ""
  label: "Navigation Item"
  defaultOpen: false
  navBlocks: []

_inputs:
  href:
    type: url
    label: Link URL
    comment: The URL that the navigation item should link to.
  label:
    type: text
    label: Label
    comment: The text label for the navigation item.
  defaultOpen:
    type: boolean
    label: Default Open
    comment: Whether the dropdown should be open by default (for items with children).
