spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Smart Video
  description: "Play a video from YouTube, Vimeo, or your local files."
  icon: videocam
  tags: []
  preview:
    icon: videocam
    text:
      - template: Smart Video - {videoType}
      - Smart Video
    subtext:
      - key: title
      - key: videoSrc
      - Add video source

blueprint:
  type: youtube
  id:
  source:
  previewImage:
  title:

preview:

_inputs:
  type:
    type: select
    options:
      values:
        - id: youtube
          name: Youtube
        - id: vimeo
          name: Vimeo
        - id: native
          name: Native
  id:
    comment: Enter a video ID from a public video on YouTube or Vimeo.
    hidden: 'type == "native"'
  source:
    type: file
    label: Video Source
    comment: For native type, the path to the video file. Must be mp4.
    options:
      accepts_mime_types:
        - video/mp4
      paths:
        uploads: /src/assets/videos/
    hidden: 'type != "native"'
  previewImage:
    comment: The image displayed before the video plays or while it is loading.
    hidden: 'type != "native"'
  title:
    comment: The title of the video for accessibility and fallback links.
  autoplay:
    comment: Play the video automatically on load without the user pressing play.
