spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Grid
  description: "Responsive, centered grid with configurable sizing."
  icon: grid_on
  tags: []

blueprint:
  label: ""
  layout: features
  minItemWidth: 280
  maxItemWidth: 400
  items: []

preview:

_inputs:
  label:
    comment: Optional label for the grid to help identify it in the editor.
    type: text
  layout:
    comment: Choose the layout style for your grid content.
    type: select
    options:
      values:
        - id: features
          name: Features
        - id: flow
          name: Flow
        - id: tiles
          name: Tiles
  minItemWidth:
    comment: The minimum width for each grid item in pixels.
    type: number
  maxItemWidth:
    comment: The maximum width for each grid item in pixels.
    type: number
  items:
    label: Grid Items
    comment: Array of grid items, each containing content blocks to render.
    type: array
    options:
      structures: _structures.grid_item

_structures:
  grid_item:
    values:
      - value:
          contentBlocks: []
        _inputs:
          contentBlocks:
            type: array
            comment: Content blocks to render within this grid item.
            options:
              structures: _structures.contentBlocks
        preview:
          icon: grid_view
