spec:
  structures:
    - containerBlocks
    - splitBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Grid
  description: "Responsive, centered grid with configurable sizing."
  icon: grid_on
  tags: []
  preview:
    text:
      - key: label
      - Grid
    subtext:
      - template: A grid containing {items|array_length} {"item"|pluralize=items}
      - Add items to the grid

blueprint:
  label: ""
  layout: features
  minItemWidth: 280
  maxItemWidth: 400
  items: []

preview:

_inputs:
  label:
    comment: Optional label for the grid to help identify it in the editor.
    type: text
  layout:
    comment: Choose the layout style for your grid content.
    type: select
    options:
      values:
        - id: features
          name: Features
        - id: flow
          name: Flow
        - id: tiles
          name: Tiles
  minItemWidth:
    comment: The minimum width for each grid item in pixels.
    type: number
  maxItemWidth:
    comment: The maximum width for each grid item in pixels.
    type: number
  items:
    label: Grid Items
    comment: Array of grid items, each containing content blocks to render.
    type: array
    options:
      structures: _structures.gridItems

_structures:
  gridItems:
    values:
      - label: Grid Item
        value:
          contentBlocks: []
        preview:
          icon: grid_view
          text: Grid Item
          subtext:
            - template: Contains {contentBlocks|array_length} content {"block"|pluralize=contentBlocks}
            - Add one or more content blocks to the grid item
        _inputs:
          contentBlocks:
            type: array
            comment: Content blocks to render within this grid item.
            options:
              structures: _structures.gridItemBlocks
