spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Accordion
  description: Hides content behind an expandable menu.
  icon: expand_all
  tags:

blueprint:
  label: ""
  items:
  openFirst: false
  singleOpen: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  singleOpen: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the accordion to help identify it in the editor.
    type: text
  items:
    type: array
    comment: The items to display in the accordion.
    icon: expand_all
    options:
      structures: _structures.accordion_item
  openFirst:
    type: switch
    comment: If true, the first item will be open by default.
  singleOpen:
    type: switch

    comment: If true, only one item can be open at a time within this accordion.
_structures:
  accordion_item:
    values:
      - label: Item
        icon: place_item
        value:
          title:
          contentBlocks:
        _inputs:
          title:
            comment: The title of the accordion item.
            type: text
          contentBlocks:
            type: array
            options:
              structures: _structures.contentBlocks
