spec:
  structures:
  label: Icon
  description: Displays an icon from your icon library.
  icon: star
  tags: []

blueprint:
  name:
  size: lg
  background: none

preview:

_inputs:
  name:
    type: select
    comment: The name of the icon to display from the icon library.
    options:
      values: _select_data.icons
      preview:
        text:
          - key: name
        image:
          - template: "src/icons/{id}.svg"
  size:
    type: select
    comment: The size of the icon.
    options:
      values:
        - id: none
          name: None
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
  background:
    type: select
    comment: The background style for the icon.
    options:
      values:
        - id: none
          name: None
        - id: subtle
          name: Subtle
