spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Simple Text
  description: "Displays blocks of text for content sections with options for alignment, size and decoration."
  icon: view_headline
  tags: []

blueprint:
  text:
  align: start
  size: md

preview:

_inputs:
  text:
    comment: The text content of the simple text.
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  align:
    comment: The alignment of the text.
    type: select
    options:
      values:
        - start
        - center
        - end
  size:
    type: select
    comment: The font size of the text.
    options:
      values:
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
        - name: 3xl
          value: 3xl
        - name: 4xl
          value: 4xl
        - name: 5xl
          value: 5xl
        - name: 6xl
          value: 6xl
      value_key: value
      preview:
        text:
          - key: name
