spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Button Group
  description: "Controls the alignment and direction of buttons."
  icon: rectangle
  tags: []
  preview:
    text:
      - key: label
      - Button Group
    subtext:
      - template: 'A button group containing {buttonBlocks|array_length} {"button"|pluralize=buttonBlocks}'
      - Add one or more buttons to the button group

blueprint:
  label:
  buttonBlocks: []
  direction: row
  alignX: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the button group to help identify it in the editor.
    type: text
  buttonBlocks:
    type: array
    comment: Array of button components to render within the group.
    options:
      structures: _structures.buttonBlocks
  direction:
    comment: Direction of button layout.
    type: select
    options:
      values:
        - id: row
          name: Row
        - id: column
          name: Column
  alignX:
    comment: The horizontal alignment of the buttons within the group.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
