spec:
  structures:
    - containerBlocks
    - pageBlocks
  label: Container
  description: "A container component that provides layout structure with background options, padding, and content width controls."
  icon: width_full
  tags: []
  preview:
    text:
      - key: label
      - Container
    subtext:
      - template: A container containing {contentBlocks|array_length} content {"block"|pluralize=slides}
      - Add content blocks to the container

blueprint:
  label: ""
  contentBlocks: []
  maxContentWidth: md
  paddingHorizontal: md
  paddingVertical: md
  colorScheme: default
  backgroundColor:
  backgroundImage:
    source: ""
    alt: ""
    positionVertical: top
    positionHorizontal: center
  rounded: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    comment: Optional label for the container to help identify it in the editor.
  contentBlocks:
    type: array
    comment: Array of content blocks to render within the container.
    options:
      structures: _structures.containerBlocks
  maxContentWidth:
    type: select
    comment: Maximum width constraint for the content.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2XL
        - id: 3xl
          name: 3xl
  paddingHorizontal:
    type: select
    comment: Horizontal padding applied to the container content.
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
  paddingVertical:
    type: select
    comment: Vertical padding applied to the container content.
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
  colorScheme:
    type: select
    comment: Color scheme theme for the container.
    options:
      values:
        - id: default
          name: Default
        - id: contrast
          name: Contrast
  backgroundColor:
    type: select
    comment: Background color for the container.
    options:
      values:
        - id: base
          name: Base
        - id: surface
          name: Surface
        - id: accent
          name: Accent
        - id: highlight
          name: Highlight
  backgroundImage:
    type: object
    comment: Background image configuration for the container.
    options:
      preview:
        icon: image
        text:
          - key: alt
          - Background Image
        subtext:
          - key: source
          - Add an image source
        image:
          - key: source
  backgroundImage.source:
    comment: URL or path to the background image.
    type: image
    options:
      paths:
        uploads: src/assets/images
        static: ""
  backgroundImage.alt:
    comment: Alt text for the background image.
    type: textarea
  backgroundImage.positionVertical:
    comment: Vertical position of the background image.
    type: select
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
  backgroundImage.positionHorizontal:
    comment: Horizontal position of the background image.
    type: select
    options:
      values:
        - id: left
          name: Left
        - id: center
          name: Center
        - id: right
          name: Right
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the container.
