spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Content Selector
  description: Switches between related content panels using tab buttons.
  icon: view_sidebar
  tags:

blueprint:
  items:
  navigationPosition: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    type: array
    options:
      structures: _structures.content_items
  navigationPosition:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: top
          name: Top

_structures:
  content_items:
    values:
      - label: Item
        icon: place_item
        value:
          title:
          contentBlocks:
        _inputs:
          title:
            type: text
            comment: The heading for the content panel.
          contentBlocks:
            type: array
            options:
              structures: _structures.contentBlocks
