spec:
  structures:
    - containerBlocks
    - splitBlocks
    - carouselBlocks
  label: Content Selector
  description: Switches between related content panels using tab buttons.
  icon: view_sidebar
  tags:
  preview:
    text:
      - key: label
      - Content Selector
    subtext:
      - template: A content selector containing {items|array_length} {"item"|pluralize=items}
      - Add items to the content selector

blueprint:
  label: ""
  items:
  navigationPosition: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the content selector to help identify it in the editor.
    type: text
  items:
    type: array
    options:
      structures: _structures.contentSelectorItems
  navigationPosition:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: top
          name: Top

_structures:
  contentSelectorItems:
    values:
      - label: Content Selector Item
        icon: place_item
        value:
          title:
          contentBlocks:
        preview:
          text:
            - key: title
            - Content Selector Item
          subtext:
            - template: A content selector item containing {contentBlocks|array_length} content {"block"|pluralize=contentBlocks}
            - Add content to the content selector item
        _inputs:
          title:
            type: text
            comment: The heading for the content panel.
          contentBlocks:
            type: array
            options:
              structures: _structures.contentSelectorBlocks
