spec:
  structures:
    - formBlocks
  label: Textarea
  description: "A multi-line text input field with an optional label."
  icon: text_ad
  tags: []
  preview:
    subtext:
      - key: label
      - key: name
      - Enter a name for the textarea input.

blueprint:
  label:
  name:
  required: false
  placeholder:
  value:

preview:

_inputs:
  label:
    type: text
    comment: The label text for the textarea field.
  name:
    type: text
    comment: A unique name attribute for the textarea field.
    options:
      required: true
      required_message: Only form elements with a name will have their values passed when submitting a form.
  required:
    type: switch
    comment: Whether the field is required.
  placeholder:
    type: text
    comment: Placeholder text for the textarea field.
  value:
    type: text
    comment: The default value for the textarea field.
