# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Blog Grid
  description: "A responsive blog block that displays an array of blog posts in a grid layout using cards. Each post includes an image, title, excerpt, and date."
  icon: article
  tags: ["blog", "content", "grid", "cards"]

# Defines the structure of this component, as well as the default values
blueprint:
  blogPosts: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  blogPosts:
    type: array
    comment: "Array of blog posts to display in the grid."
