spec:
  structures:
    - buttonBlocks
  label: Button
  description: "A clickable element that navigates to another page or triggers an action within the current page."
  icon: rectangle
  tags: []

blueprint:
  text:
  link:
  iconName:
  iconPosition: before
  hideText: false
  variant: ghost
  size: md

preview:

_inputs:
  text:
    type: text
    comment: The text that goes inside the button.
  link:
    type: url
    comment: The URL that the button should link to.
  iconName:
    type: select
    comment: The name of the icon to display. See the Icon component documentation for more information.
    options:
      values: _select_data.icons
  iconPosition:
    type: select
    options:
      values:
        - id: before
          name: Before
        - id: after
          name: After
    comment: The position of the icon relative to the text.
  hideText:
    type: switch
    comment: Whether to hide the button text and show only the icon.
  variant:
    type: select
    options:
      values:
        - id: primary
          name: Primary
        - id: secondary
          name: Secondary
        - id: tertiary
          name: Tertiary
        - id: ghost
          name: Ghost
        - id: text
          name: Text
    comment: The presentation of button.
  size:
    type: select
    options:
      values:
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
    comment: The size of the button.
