spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Simple Text
  description: "Displays plain text in layouts with configurable size and alignment."
  icon: view_headline
  tags: []
  preview:
    subtext:
      - key: text
      - Add text to block

blueprint:
  text:
  alignX: start
  size: md

preview:

_inputs:
  text:
    comment: The text content of the simple text.
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  alignX:
    comment: The horizontal alignment of the text.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  size:
    type: select
    comment: The font size of the text.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
