spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Counter
  description: Animated number that counts up when visible.
  icon: speed
  tags: []
  preview:
    subtext:
      - template: "{prefix}{number}{suffix}"
      - Add counter details

blueprint:
  number:
  prefix:
  suffix:
  alignX: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  number:
    type: number
    comment: The number to count to.
    options:
      min: 0
      step: 1
  prefix:
    comment: Text immediately before the number.
  suffix:
    comment: Text immediately after the number.
  alignX:
    comment: The horizontal alignment of the counter.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
