spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Form
  description: "A form element that groups related form controls and handles form submission."
  icon: checklist_rtl
  tags: []
  preview:
    subtext:
      - template: A form containing {formBlocks|array_length} {"item"|pluralize=formBlocks}
      - Add items to the form

blueprint:
  action:
  formBlocks: []

preview:

_inputs:
  action:
    type: url
    comment: Where to send the form-data when the form is submitted. The URL that processes the form submission.
  formBlocks:
    type: array
    comment: The form blocks to render inside the form.
    options:
      structures: _structures.formBlocks
