spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Split
  description: Arranges content in two columns.
  icon: vertical_split
  tags: []

blueprint:
  firstColumnContentBlocks: []
  secondColumnContentBlocks: []
  distributionMode: half
  fixedWidth: null
  verticalAlignment: top
  reverse: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    comment: Optional label for the split to help identify it in the editor.
  firstColumnContentBlocks:
    type: array
    comment: Array of content blocks to render in the first column.
    options:
      structures: _structures.contentBlocks
  secondColumnContentBlocks:
    type: array
    comment: Array of content blocks to render in the second column.
    options:
      structures: _structures.contentBlocks
  distributionMode:
    type: select
    comment: Predefined distribution mode for both columns.
    options:
      values:
        - id: quarter-three-quarters
          name: Quarter-Three-Quarters
        - id: third-two-thirds
          name: Third-Two-Thirds
        - id: half
          name: Half
        - id: two-thirds-third
          name: Two-Thirds-Third
        - id: three-quarters-quarter
          name: Three-Quarters-Quarter
        - id: fixed-flexible
          name: Fixed-Flexible
        - id: flexible-fixed
          name: Flexible-Fixed
  fixedWidth:
    type: number
    comment: Used when distribution mode includes 'fixed'. Sets the width in pixels for the fixed column.
  verticalAlignment:
    type: select
    comment: Vertical alignment of the columns.
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
        - id: stretch
          name: Stretch
  reverse:
    type: switch
    comment: Swaps the order of the columns.
