spec:
  structures:
    - containerBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Split
  description: Arranges content in two columns.
  icon: vertical_split
  tags: []
  preview:
    text:
      - key: label
      - Split
    subtext:
      - template: A split containing {firstColumnContentBlocks|array_length} content {"block"|pluralize=firstColumnContentBlocks} in the first column, and {secondColumnContentBlocks|array_length} content {"block"|pluralize=secondColumnContentBlocks} in the second column
      - Add items to the split

blueprint:
  label: ""
  firstColumnContentBlocks: []
  secondColumnContentBlocks: []
  distributionMode: half
  fixedWidth: null
  minSplitWidth: 0
  verticalAlignment: top
  reverse: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the split to help identify it in the editor.
    type: text
  firstColumnContentBlocks:
    type: array
    comment: Array of content blocks to render in the first column.
    options:
      structures: _structures.splitBlocks
  secondColumnContentBlocks:
    type: array
    comment: Array of content blocks to render in the second column.
    options:
      structures: _structures.splitBlocks
  distributionMode:
    comment: Predefined distribution mode for both columns.
    type: select
    options:
      values:
        - id: quarter-three-quarters
          name: Quarter-Three-Quarters
        - id: third-two-thirds
          name: Third-Two-Thirds
        - id: half
          name: Half
        - id: two-thirds-third
          name: Two-Thirds-Third
        - id: three-quarters-quarter
          name: Three-Quarters-Quarter
        - id: fixed-flexible
          name: Fixed-Flexible
        - id: flexible-fixed
          name: Flexible-Fixed
  fixedWidth:
    comment: Fixed width in pixels for the fixed column (used when distribution mode includes 'fixed').
    type: number
  minSplitWidth:
    comment: Minimum width in pixels before switching to mobile layout.
    type: number
  verticalAlignment:
    comment: Vertical alignment of the columns.
    type: select
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
        - id: stretch
          name: Stretch
  reverse:
    comment: Swaps the order of the columns.
    type: switch
