spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Divider
  description: A horizontal line to separate content
  icon: horizontal_rule
  tags:
  preview:
    text: Divider
    subtext:
      - key: paddingVertical
      - Add a padding value
    icon: horizontal_rule

blueprint:
  paddingVertical:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  paddingVertical:
    comment: The space on the top and bottom of the horizontal line.
    type: select
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
