spec:
  structures:
    - containerBlocks
    - splitBlocks
    - gridItemBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Card
  description: "A container component that provides card layout with background options and padding controls."
  icon: crop_square
  tags: []
  preview:
    text:
      - key: label
      - Card

blueprint:
  label:
  contentBlocks: []
  headerContentBlocks: []
  footerContentBlocks: []
  paddingHorizontal: sm
  paddingVertical: sm
  colorScheme: "default"
  backgroundColor:
  backgroundImage:
    source:
    alt:
    positionVertical: top
    positionHorizontal: center
  link:
  rounded: false
  border: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
    comment: Optional label for the card to help identify it in the editor.
  contentBlocks:
    type: array
    comment: Array of content blocks to render within the card.
    options:
      structures: _structures.cardBlocks
  headerContentBlocks:
    type: array
    comment: Array of content blocks to render in the card header.
    options:
      structures: _structures.cardBlocks
  footerContentBlocks:
    type: array
    comment: Array of content blocks to render in the card footer.
    options:
      structures: _structures.cardBlocks
  paddingHorizontal:
    type: select
    comment: Horizontal padding applied to the card content.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xL
  paddingVertical:
    type: select
    comment: Vertical padding applied to the card content.
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2XL
  colorScheme:
    type: select
    comment: Color scheme theme for the card.
    options:
      values:
        - id: default
          name: Default
        - id: contrast
          name: Contrast
  backgroundColor:
    type: select
    comment: Background color for the card.
    options:
      values:
        - id: base
          name: Base
        - id: surface
          name: Surface
        - id: accent
          name: Accent
        - id: highlight
          name: Highlight
  backgroundImage:
    type: object
    comment: Background image configuration for the card.
    options:
      preview:
        icon: image
        text:
          - key: alt
          - Background Image
        subtext:
          - key: source
          - Add an image source
        image:
          - key: source
  backgroundImage.source:
    comment: URL or path to the background image.
    type: image
    options:
      paths:
        uploads: src/assets/images
        static: ""
  backgroundImage.alt:
    comment: Alt text for the background image.
    type: text
  backgroundImage.positionVertical:
    comment: Vertical position of the background image.
    type: select
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
  backgroundImage.positionHorizontal:
    comment: Horizontal position of the background image.
    type: select
    options:
      values:
        - id: left
          name: Left
        - id: center
          name: Center
        - id: right
          name: Right
  link:
    type: url
    comment: URL to make the entire card clickable. Leave empty for a non-clickable card.
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the card.
  border:
    type: switch
    comment: Whether to apply a border to the card.
