spec:
  structures:
    - formBlocks
  label: Submit
  description: "A submit button for forms."
  icon: check
  tags: []
  preview:
    text:
      - key: text
      - key: iconName
      - Submit Button
    subtext: A submit button for forms.

blueprint:
  text: Submit
  variant: primary
  size: md
  iconName:
  iconPosition: before
  hideText: false
  disabled: false

preview:

_inputs:
  text:
    type: text
    comment: The text that goes inside the submit button.
    hidden: "hideText"
  variant:
    type: select
    comment: The presentation of the submit button.
    options:
      values:
        - id: primary
          name: Primary
        - id: secondary
          name: Secondary
        - id: tertiary
          name: Tertiary
        - id: ghost
          name: Ghost
        - id: text
          name: Text
  size:
    type: select
    comment: The size of the submit button.
    options:
      values:
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
  iconName:
    type: select
    comment: The name of the icon to display. See the Icon component documentation for more information.
    options:
      values: _select_data.icons
      preview:
        text:
          - key: name
        image:
          - template: "src/icons/{id}.svg"
  iconPosition:
    type: select
    comment: The position of the icon relative to the text.
    hidden: "!iconName"
    options:
      values:
        - id: before
          name: Before
        - id: after
          name: After
  hideText:
    type: switch
    comment: Whether to hide the button text and show only the icon.
    hidden: '!iconName"'
  disabled:
    type: switch
    comment: Whether the submit button is disabled.
