spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: List
  description: Displays items in a list with icons as markers. (For traditional bulleted or numbered lists, use rich text instead.)
  icon: list
  tags:

blueprint:
  items:
  direction: vertical
  horizontalAlignment: start
  size: md

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    type: array
    options:
      structures: _structures.item
    comment: Array of list items. If empty, slot content will be used instead.
  direction:
    type: select
    options:
      values:
        - id: horizontal
          name: Horizontal
        - id: vertical
          name: Vertical
    comment: The direction in which list items are arranged.
  horizontalAlignment:
    type: select
    comment: The alignment of the list items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  size:
    comment: Controls the size of the icon and text.
    type: select
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2XL

_structures:
  item:
    values:
      - label: List Item
        icon: text_fields
        value:
          text: ""
          icon:
        _inputs:
          text:
            type: markdown
            options:
              bold: true
              italic: true
              link: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              undo: true
              redo: true
              removeformat: true
              copyformatting: true
          icon:
            type: select
            comment: The name of the icon to display from the icon library.
            options:
              values: _select_data.icons
