spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: List
  description: Displays items in a list with icons as markers. (For traditional bulleted or numbered lists, use rich text instead.)
  icon: list
  tags: []
  preview:
    subtext:
      - template: Contains {items|array_length} list {'item'|pluralize=items}
      - Add list items

blueprint:
  items:
  direction: vertical
  alignX: start
  size: md

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items:
    type: array
    options:
      structures: _structures.listItems
    comment: Array of list items.
  direction:
    type: select
    options:
      values:
        - id: horizontal
          name: Horizontal
        - id: vertical
          name: Vertical
    comment: The direction in which list items are arranged.
  alignX:
    type: select
    comment: The horizontal alignment of the list items.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  size:
    comment: Controls the size of the icon and text.
    type: select
    options:
      values:
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl

_structures:
  listItems:
    values:
      - label: List Item
        value:
          text: ""
          icon:
        preview:
          icon: text_fields
          image:
            - template: "src/icons/{icon}.svg"
        _inputs:
          text:
            type: markdown
            comment: The text to display in the list item.
            options:
              bold: true
              italic: true
              link: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              undo: true
              redo: true
              removeformat: true
              copyformatting: true
          icon:
            type: select
            comment: The name of the icon to display from the icon library.
            options:
              values: _select_data.icons
              preview:
                text:
                  - key: name
                image:
                  - template: "src/icons/{id}.svg"
