spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Smart Image
  description: Displays an image optimized for performance with smart CDN detection.
  icon: image
  tags: []
  preview:
    icon: image
    text: Smart Image
    subtext:
      - key: alt
      - key: source
      - Add image source

blueprint:
  source:
  alt:
  rounded: false
  aspectRatio: null
  positionVertical: center
  positionHorizontal: center

preview:

_inputs:
  source:
    type: image
    comment: The URL or path to the image.
    options:
      paths:
        uploads: src/assets/images
        static: ""
  alt:
    type: textarea
    comment: Alternative text for accessibility.
  rounded:
    type: switch
    comment: Whether to apply rounded corners to the image.
  aspectRatio:
    type: select
    comment: Set a fixed aspect ratio for the image.
    options:
      values:
        - id: square
          name: Square (1:1)
        - id: landscape
          name: Landscape (4:3)
        - id: portrait
          name: Portrait (3:4)
        - id: widescreen
          name: Widescreen (16:9)
        - id: golden
          name: Golden (1.618:1)
  positionVertical:
    type: select
    comment: Vertical positioning of the image within the container.
    options:
      values:
        - id: top
          name: Top
        - id: center
          name: Center
        - id: bottom
          name: Bottom
  positionHorizontal:
    type: select
    comment: Horizontal positioning of the image within the container.
    options:
      values:
        - id: left
          name: Left
        - id: center
          name: Center
        - id: right
          name: Right
