# Metadata about this component, to be used in the CMS
spec:
  structures:
    - nav_blocks
  label: Nav List
  description: A list container for navigation items.
  icon: list
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  navBlocks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  navBlocks: []
