spec:
  structures:
    - formBlocks
  label: Input
  description: "A form input field with an optional label."
  icon: rectangle
  tags: []
  preview:
    text:
      - template: Input - {type}
    subtext:
      - key: label
      - key: name
      - A form input field with an optional label.

blueprint:
  label:
  name:
  type: text
  placeholder:
  required: false
  value:

preview:

_inputs:
  label:
    type: text
    comment: The label text for the input field.
  name:
    type: text
    comment: The name attribute for the input field.
  type:
    type: select
    options:
      values:
        - text
        - email
        - password
        - tel
        - url
        - number
    comment: The input type.
  placeholder:
    type: text
    comment: Placeholder text for the input field.
  required:
    type: switch
    comment: Whether the field is required.
  value:
    type: text
    comment: The default value for the input field.
