spec:
  structures:
    - formBlocks
  label: Hidden
  description: "A hidden form field for storing data that should not be visible to users."
  icon: eye-slash
  tags: []
  preview:
    text:
      - template: Hidden - {name}
    subtext: A hidden form field for storing data that should not be visible to users.

blueprint:
  name: ""
  value: ""

preview:

_inputs:
  name:
    type: text
    comment: The name attribute for the hidden input field.
  value:
    type: text
    comment: The value to be stored in the hidden field.
