spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Video
  description: "Play a video from YouTube, Vimeo, or your local files."
  icon: videocam
  tags: []
  preview:
    icon: videocam
    text:
      - template: Video - {videoType}
      - Video
    subtext:
      - key: title
      - key: videoSrc
      - Add video source

blueprint:
  videoType: youtube
  videoId:
  videoSrc:
  videoPoster:
  title:

preview:

_inputs:
  videoType:
    type: select
    options:
      values:
        - id: youtube
          name: Youtube
        - id: vimeo
          name: Vimeo
        - id: native
          name: Native
  videoId:
    type: text
    comment: Enter a video ID from a public video on YouTube or Vimeo.
    hidden: 'videoType == "native"'
  videoSrc:
    type: file
    label: Video Source
    comment: Must be mp4 as this is supported by all modern browsers.
    options:
      accepts_mime_types:
        - video/mp4
      paths:
        uploads: /src/assets/videos/
    hidden: 'videoType != "native"'
  videoPoster:
    type: image
    comment: The image displayed before the video plays or while it is loading.
    hidden: 'videoType != "native"'
  autoplay:
    comment: Play the video automatically on load without the user pressing play.
