spec:
  structures:
    - containerBlocks
    - splitBlocks
    - contentSelectorBlocks
  label: Carousel
  description: "A carousel component for displaying slides with navigation controls"
  icon: image
  tags: []
  preview:
    text:
      - key: label
      - Carousel
    subtext:
      - template: A carousel containing {slides|array_length} {"slide"|pluralize=slides}
      - Add slides to the carousel

blueprint:
  label: ""
  slides: []
  autoPlay: false
  autoScroll: false
  slideWidthPercent: 100
  minSlideWidth: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: Optional label for the carousel to help identify it in the editor.
    type: text
  slides:
    comment: Array of slides to display in the carousel.
    type: array
    options:
      structures: _structures.slides
  autoPlay:
    comment: Enable auto-play functionality.
    type: switch
  autoScroll:
    comment: Enable auto-scroll functionality.
    type: switch
  slideWidthPercent:
    comment: Width of each slide as a percentage of the carousel (e.g., 33, 50, 100).
    type: range
    min: 0
    max: 100
    step: 1
  minSlideWidth:
    comment: Minimum width of slides in pixels. Prevents slides from getting too small.
    type: number

_structures:
  slides:
    values:
      - label: Carousel Slide
        value:
          contentBlocks: []
        _inputs:
          contentBlocks:
            type: array
            options:
              structures: _structures.carouselBlocks
        preview:
          icon: transition_slide
          text: Carousel Slide
          subtext:
            - template: Contains {contentBlocks|array_length} content {"block"|pluralize=contentBlocks}
            - Add one or more content blocks to the grid item
