spec:
  structures:
    - content_blocks
  label: Definition List
  description: "Useful for displaying key-value pairs, ideal for glossaries, opening times, etc."
  icon: dns
  tags: []

blueprint:
  items:
  horizontal_gap: sm
  vertical_gap: sm

preview:

_inputs:
  items:
    type: array
    options:
      structures: _structures.item
  vertical_gap:
    type: select
    options:
      values:
        - name: None
          value: none
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
      value_key: value
      preview:
        text:
          - key: name
  horizontal_gap:
    type: select
    options:
      values:
        - name: None
          value: none
        - name: Extra Small
          value: xs
        - name: Small
          value: sm
        - name: Medium
          value: md
        - name: Large
          value: lg
        - name: Extra Large
          value: xl
        - name: 2xl
          value: 2xl
      value_key: value
      preview:
        text:
          - key: name

_structures:
  item:
    values:
      - label: Definition List Item
        icon: title
        value:
          title:
          content:
