spec:
  structures:
    - formBlocks
  label: Select
  description: "A dropdown select field with an optional label."
  icon: view_list
  tags: []
  preview:
    subtext:
      - key: label
      - key: name
      - Enter a name for the form input.

blueprint:
  label:
  name:
  required: false
  options:
    - value: "option1"
      label: "Option 1"
    - value: "option2"
      label: "Option 2"
    - value: "option3"
      label: "Option 3"
  placeholder:
  value:

preview:

_inputs:
  label:
    type: text
    comment: The label text for the select field.
  name:
    type: text
    comment: A unique name attribute for the select field.
    options:
      required: true
      required_message: Only form elements with a name will have their values passed when submitting a form.
  required:
    type: switch
    comment: Whether the field is required.
  options:
    type: array
    comment: Array of select options with value and label.
    options:
      structures: _structures.selectOptions
      min_items: 2
      min_items_message: At least two options are required.
  placeholder:
    type: text
    comment: Placeholder text for the select field.
  value:
    type: text
    comment: The default selected value.

_structures:
  selectOptions:
    values:
      - value:
          value:
          label:
        preview:
          icon: check_circle
          text:
            - key: label
            - Add a label for the select item
          subtext:
            - key: value
            - Add a value for the select item
        _inputs:
          label:
            type: text
            comment: The label text for the select option.
          value:
            type: text
            comment: The value to add to the form when the option is selected.
