spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Testimonial
  description: A quotation with an author and author description.
  icon: format_quote
  tags:
  preview:
    text:
      - template: Testimonial - {authorName}
      - Testimonial
    subtext:
      - key: text
      - Add testimonial text

blueprint:
  text:
  authorName:
  authorDescription:
  alignX: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    comment: Quotation marks will be added around the text.
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
  authorName:
    comment: The person to whom you're attributing the quotation.
    type: textarea
  authorDescription:
    comment: The role or company of the person.
    type: textarea
  alignX:
    comment: The horizontal alignment of the testimonial.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
