spec:
  structures:
    - contentBlocks
    - firstContentBlocks
    - secondContentBlocks
  label: Heading
  description: The main title or heading with levels (H1 to H6) to show hierarchy and structure for the page and sections.
  icon: title
  tags:

blueprint:
  text:
  type: h2
  size:
  align: start
  iconName: null
  iconPosition: before

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    comment: The text content of the heading.
    options:
      bold: false
      copyformatting: false
      italic: true
      link: true
      redo: true
      removeformat: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      blockquote: false
      bulletedlist: false
      image: false
      numberedlist: false
      snippet: false
  type:
    type: select
    comment: The heading type/level.
    options:
      values:
        - id: h1
          name: h1
        - id: h2
          name: h2
        - id: h3
          name: h3
        - id: h4
          name: h4
        - id: h5
          name: h5
        - id: h6
          name: h6
        - id: eyebrow
          name: Eyebrow
        - id: subtitle
          name: Subtitle
  size:
    type: select
    comment: The font size of the text.
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
  align:
    type: select
    comment: The alignment of the text.
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  iconName:
    type: select
    comment: The name of the icon to display.
    options:
      values: _select_data.icons
  iconPosition:
    type: select
    comment: The position of the icon relative to the text.
    hidden: "!iconName"
    options:
      values:
        - id: before
          name: Before
        - id: after
          name: After
