spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Heading
  description: The main title or heading with levels (H1 to H6) to show hierarchy and structure for the page and sections.
  icon: title
  tags: []
  preview:
    text:
      - template: Heading - {type}
      - Add heading type
    subtext:
      - key: text
      - Add heading text

blueprint:
  text:
  type: h2
  size:
  alignX: start
  iconName: null
  iconPosition: before

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    comment: The text content of the heading.
    type: markdown
    options:
      bold: false
      copyformatting: false
      italic: true
      link: true
      redo: true
      removeformat: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      blockquote: false
      bulletedlist: false
      image: false
      numberedlist: false
      snippet: false
  type:
    comment: The heading type or level.
    type: select
    options:
      values:
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - eyebrow
        - subtitle
  size:
    comment: The font size of the text.
    type: select
    options:
      values:
        - id: none
          name: None
        - id: xs
          name: Extra Small
        - id: sm
          name: Small
        - id: md
          name: Medium
        - id: lg
          name: Large
        - id: xl
          name: Extra Large
        - id: 2xl
          name: 2xl
        - id: 3xl
          name: 3xl
        - id: 4xl
          name: 4xl
        - id: 5xl
          name: 5xl
        - id: 6xl
          name: 6xl
  alignX:
    comment: The horizontal alignment of the text.
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
  iconName:
    comment: The name of the icon to display.
    type: select
    options:
      values: _select_data.icons
      preview:
        text:
          - key: name
        image:
          - template: "src/icons/{id}.svg"
  iconPosition:
    comment: The position of the icon relative to the text.
    type: select
    options:
      values:
        - id: before
          name: Before
        - id: after
          name: After
