spec:
  structures:
    - content_blocks
  label: Grid
  description: "Responsive, centered grid with configurable sizing."
  icon: squares-2x2
  tags: []

blueprint:
  minItemWidth: 200
  maxItemWidth: 320
  verticalAlignment: "start"
  horizontalAlignment: "center"
  equalWidth: true
  items:
    - contentBlocks:

preview:

_inputs:
  minItemWidth:
    comment: The minimum width for each grid item in pixels.
    type: number
  maxItemWidth:
    comment: The maximum width for each grid item in pixels.
    type: number
  verticalAlignment:
    comment: The vertical alignment of grid items.
    type: select
    options:
      values:
        - start
        - center
        - end
        - stretch
  horizontalAlignment:
    comment: The horizontal alignment of grid items.
    type: select
    options:
      values:
        - start
        - center
        - end
        - space-between
        - space-around
        - space-evenly
  equalWidth:
    comment: Whether items should have equal widths (true) or intrinsic widths based on content (false).
    type: boolean
  items:
    comment: Array of grid items, each containing content blocks to render.
    type: array
    _inputs:
      contentBlocks:
        comment: Content blocks to render within this grid item.
        type: array
