spec:
  structures:
    - containerBlocks
    - cardBlocks
    - splitBlocks
    - gridItemBlocks
    - accordionBlocks
    - carouselBlocks
    - contentSelectorBlocks
  label: Rich text
  description: A catch-all for all content types. Can contain headings, paragraphs, images, bullets. Use text prop for Markdown content or slot for HTML content.
  icon: edit_note
  tags: []
  preview:
    subtext:
      - key: text
      - Add text to block

blueprint:
  text:
  alignX: start

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    comment: The content for the rich text component (Markdown format). Leave empty to use slot content instead.
    type: markdown
    options:
      bold: true
      italic: true
      link: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      undo: true
      redo: true
      format: p h1 h2 h3 h4 h5 h6
      removeformat: true
      copyformatting: true
      bulletedlist: true
      numberedlist: true
      indent: true
      outdent: true
      join_above: true
      join_below: true
      code: true
      embed: true
      horizontalrule: true
      image: true
      table: true
  alignX:
    type: select
    options:
      values:
        - id: start
          name: Start
        - id: center
          name: Center
        - id: end
          name: End
    comment: The horizontal alignment of the rich text component.
